-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS PROCESSED;

-- Luas Passengers Table (Raw data as it comes from CSO)
CREATE OR REPLACE TABLE RAW.LUAS_PASSENGERS (
    STATISTIC VARCHAR(50),
    STATISTIC_LABEL VARCHAR(100),
    TLIST VARCHAR(50),
    YEAR NUMBER,
    C01885V02316 VARCHAR(10),
    MONTH VARCHAR(20),
    UNIT VARCHAR(20),
    VALUE NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dublin Bus Passengers Table (Raw data as it comes from CSO)
CREATE OR REPLACE TABLE RAW.DUBLIN_BUS_PASSENGERS (
    STATISTIC VARCHAR(50),
    STATISTIC_LABEL VARCHAR(100),
    TLIST VARCHAR(50),
    YEAR NUMBER,
    C01885V02316 VARCHAR(10),
    MONTH VARCHAR(20),
    UNIT VARCHAR(20),
    VALUE NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Weather Data Table (Raw data structure from Met Éireann)
CREATE OR REPLACE TABLE DUBLIN_TRANSPORTATION.RAW.WEATHER_DATA (
    DATE DATE,
    IND1 NUMBER,             -- First "ind" column
    RAINFALL_MM FLOAT,       -- Rainfall in mm
    IND2 NUMBER,             -- Second "ind" column
    MAXT FLOAT,              -- Maximum temperature
    IND3 NUMBER,             -- Third "ind" column
    MINT FLOAT,              -- Minimum temperature
    GMIN FLOAT,              -- Ground minimum temperature
    SOIL FLOAT,              -- Soil temperature
    CREATED_AT TIMESTAMP_NTZ -- Timestamp for data creation
);

-- Dublin Bikes Table (Raw data from API)
CREATE OR REPLACE TABLE RAW.DUBLIN_BIKES (
    SYSTEM_ID VARCHAR(50),
    LAST_REPORTED TIMESTAMP_NTZ,
    STATION_ID VARCHAR(50),
    NUM_BIKES_AVAILABLE NUMBER,
    NUM_DOCKS_AVAILABLE NUMBER,
    IS_INSTALLED BOOLEAN,
    IS_RENTING BOOLEAN,
    IS_RETURNING BOOLEAN,
    NAME VARCHAR(100),
    SHORT_NAME VARCHAR(100),
    ADDRESS VARCHAR(200),
    LAT FLOAT,
    LON FLOAT,
    REGION_ID VARCHAR(50),
    CAPACITY NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Cycle Counts Table (Raw data structure)
CREATE OR REPLACE TABLE RAW.CYCLE_COUNTS (
    TIMESTAMP TIMESTAMP_NTZ,
    LOCATION VARCHAR(200),
    DIRECTION VARCHAR(50),
    COUNT NUMBER,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
